services:
  - type: web
    name: travel-booking-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
